# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
