# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20170302_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Опубликовано'),
        ),
    ]
