# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20170305_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=3000, verbose_name='комментарий'),
        ),
    ]
